// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "MicroCode",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .executable(name: "MicroCode", targets: ["MicroCode"]),
        .library(name: "MicroCodeCore", targets: ["MicroCodeCore"])
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm.git", from: "1.0.0")
    ],
    targets: [
        .target(
            name: "MicroCodeSupport",
            dependencies: [],
            path: "MicroCodeSupport",
            publicHeadersPath: "include"
        ),
        .target(
            name: "MicroCodeKernel",
            dependencies: [],
            path: "MicroCodeKernel",
            publicHeadersPath: "include"
        ),
        .target(
            name: "MicroCodeCore",
            dependencies: ["MicrocodeCoreSupport"],
            path: "MicroCodeCore/Sources"
        ),
        .executableTarget(
            name: "MicroCode",
            dependencies: ["MicroCodeSupport", "MicroCodeKernel", "SwiftTerm", "MicrocodeCoreSupport", "MicroCodeCore"],
            path: "MicroCode",
            exclude: [
                "Views/Design/DesignModeView.swift",
                "Views/Design/DesignLayersPanel.swift",
                "Views/Design/DesignToolbar.swift",
                "Views/Design/PropertiesInspector.swift",
                "Views/Design/DesignRulerView.swift"
            ],
            sources: [
                "MicroCodeApp.swift",
                "Services/DeveloperToolsGuard.swift",
                "Services/CrashReporter.swift",
                "Managers/ReportLogManager.swift",
                "Managers/PDFGenerator.swift",
                "Models/AppState.swift",
                "Models/AnyCodable.swift",
                "Models/CellModels.swift",
                "Models/MicFormat.swift",
                "Models/SubAgentModels.swift",
                "Services/SubAgentHarness.swift",
                "Views/AI/SubAgentMonitorView.swift",
                "Services/BackendService.swift",
                "Services/TerminalService.swift",
                "Services/SimulatorManager.swift",
                "Services/CodeAnalyzer.swift",
                "Services/ExportService.swift",
                "Views/SymbolEffectModifier.swift",
                "Views/ContentView.swift",
                "Views/AIProviderBrandIcon.swift",
                "Views/FirstLaunchWelcomeView.swift",
                "Views/RefactorProWindow.swift",
                "Views/ExpandCodeWindow.swift",
                "Views/FormatCodeWindow.swift",
                "Views/CodeAnalysisWindow.swift",

                "Views/PlaygroundView.swift",
                "Views/PlaygroundCellView.swift",
                "Views/DocumentViewer.swift",
                "Views/CatalogueSidebar.swift",
                "Views/SyntaxHighlighter.swift",
                "Views/StatusBarView.swift",
                "Views/FileTabBar.swift",
                "Views/NotebookView.swift",
                "Views/DotnetProjectView.swift",
                "Services/DotnetService.swift",
                "Models/MLModels.swift",
                "Services/MLTrainer.swift",
                "Views/AI/AITrainerView.swift",
                "Views/AI/AIAgentView.swift",
                "Views/TeamTasksView.swift",
                "Views/ScienceModeView.swift",
                "Services/ScienceService.swift",
                "Services/ScienceWorkspaceStore.swift",
                "Services/ProjectManager.swift",
                "Services/DeviceRuntimeService.swift",
                "Services/AppleSimulatorCaptureService.swift",
                "Services/NativeSimulatorBridgeService.swift",
                "Services/ServeSimService.swift",
                "Services/XcodeBuildParser.swift",
                "Views/ProjectToolbar.swift",
                "Views/DeviceRuntimeView.swift",
                "Views/EmbeddedAndroidDeviceView.swift",
                "Views/EmbeddedAppleSimulatorView.swift",
                "Views/EmbeddedWebAppPreviewView.swift",
                "Views/EmbeddedDeviceDockView.swift",
                "Services/SubscriptionAuthManager.swift",
                "Services/DeviceCommandBarService.swift",
                "Services/NoiseCancelingLogService.swift",
                "Services/AssetMatrixService.swift",
                "Services/StoreLifecycleService.swift",
                "Views/MobileDevCommandBarView.swift",
                "Views/AssetMatrixModalView.swift",
                "Views/StoreLifecycleModalView.swift",
                "Views/BuildReportView.swift",
                "Services/PythonEnvManager.swift",
                "Services/PythonScriptNotebookBridge.swift",
                "Services/ArdiumLSPService.swift",
                "Services/ArdiumRunner.swift",
                "Services/LSPClientService.swift",
                "Services/LSPManager.swift",
                "Views/PythonEnvSheet.swift",
                "Views/EditorView.swift",
                "Views/DotnetToolbar.swift",
                "Models/ScenarioModels.swift",
                "Views/ScenarioView.swift",
                "Services/RuntimeManager.swift",
                "Views/RuntimeManagerView.swift",
                "Views/AI/CodeAnalysisView.swift",
                "Views/CodeAnalysisPanel.swift",
                "Views/GitSettingsView.swift",
                "Views/Settings/CacheSettingsView.swift",
                "Views/GitPanelView.swift",
                "Views/FilePreviewView.swift",
                "Services/ExtensionManager.swift",
                "Services/ExtensionHostService.swift",
                "Views/ExtensionSettingsView.swift",
                "Models/AICodeReport.swift",
                "Services/AgentCore/AgentToolBox.swift",
                "Services/AgentCore/AppleVisionEngine.swift",
                "Services/AuthService.swift",
                "Services/SupabaseAuthService.swift",
                "Services/CollaborationService.swift",
                "Views/EmbeddedToolsView.swift",
                "Views/EmbeddedStudioView.swift",
                "Views/EmbeddedProjectWizard.swift",
                "Services/EmbeddedEnvManager.swift",
                "Views/EmbeddedEnvSheet.swift",
                "Views/EmbeddedAIAgentPanel.swift",
                "Views/CollaborationView.swift",
                "Models/SASProcedures.swift",
                "Views/Tasks/GitHistoryView.swift", // New Phase 10
                "Views/Notebook/SASProcedureView.swift", // New Phase 12
                "Views/Notebook/NotebookAIPanel.swift", // Cell Mode AI Agent
                "Models/DesignModels.swift", // Design Engine
                "Services/DesignStore.swift",
                "Services/Design/DesignCodeGenerator.swift",
                "Views/Design/DesignCanvasView.swift",
                // "Views/Design/DesignToolbar.swift", // Replaced by FloatingToolbar
                // "Views/Design/PropertiesInspector.swift", // Replaced by Sidebar
                "Views/Design/DesignElementView.swift",
                // "Views/Design/DesignLayersPanel.swift", // Legacy - Removed
                // "Views/Design/DesignRulerView.swift", // Legacy - Removed
                "Views/Design/Components/DesignInteractionOverlay.swift",
                // "Views/Design/DesignModeView.swift", // Replaced by Workbench
                // Phase 11 Redesign
                "Views/Design/DesignWorkbenchView.swift",
                "Views/Design/DesignNavigatorSidebar.swift",
                "Views/Design/DesignInspectorSidebar.swift",
                "Views/Design/DesignFloatingToolbar.swift",
                "Services/ContainerService.swift",
                "Views/ContainerView.swift",
                "Services/PerformanceManager.swift",
                "Services/PreviewService.swift",
                "Views/PreviewView.swift",
                "Views/Components/ToolWindowWrapper.swift",
                "Views/Components/NodeVersionPicker.swift",
                "Views/Components/WebSubscriptionLoginSheet.swift",
                "Views/RemoteXView.swift",
                "Views/RemoteFileBrowser.swift",
                "Views/RemoteTerminalView.swift",
                "Services/HotReloadClient.swift",
                "Services/UITreeExtractor.swift",
                "Services/AutoHealerService.swift",
                "Services/AgentCore/HealerAgent.swift",
                "Services/AgentCore/TokenOptimizer.swift",
                "Services/DatabaseService.swift",
                "Services/DataFrameService.swift",
                "Services/APIClientService.swift",
                "Services/PreviewDockService.swift",
                "Services/CICDService.swift",
                "Services/LocalPipelineRunner.swift",
                "Services/AgentService.swift",
                "Services/AgentKernelClient.swift",
                "Services/AgentTranscriptStore.swift",
                "Services/TeamTaskService.swift",
                "Services/TeamIntegrationService.swift",
                "Services/AgentMemoryService.swift",
                "Services/AIClient.swift",            // Direct AI API Client
                "Services/TelemetryService.swift",    // Opt-in product analytics
                "Services/GitAuthService.swift",      // Hosting auth via secure vendor CLIs
                "Services/AIModelCatalog.swift",       // Shared dynamic model registry
                "Services/DotminiPlatformKeyService.swift", // Platform API-key bridge
                "Services/AIProviderAuthService.swift",// Multi-provider Auth + Keychain
                "Services/KeychainManager.swift",      // Keychain CRUD + Rust FFI Bridge
                "Services/MCPServer.swift",            // MCP Protocol Server
                "Services/LocalLLMService.swift",     // Local LLM Detection (LM Studio, Ollama)
                "Services/AIAutocompleteService.swift", // Ghost Text AI Engine
                
                "Services/MicroCodeService.swift",    // AI Core Service Wrapper
                "Kernel/ComputeKernel.swift",
                "Kernel/JupyterClient.swift",
                "Kernel/JupyterKernel.swift",
                "Kernel/RemoteGPUService.swift",
                "Kernel/RemoteProviderService.swift",
                "Kernel/CloudGPUService.swift",
                "Views/CloudGPUView.swift",
                "Views/Settings/AgentSkillsView.swift",
                "Views/Design/AIDesignPanel.swift",
                "Services/AIDesignEngine.swift",
                "Services/BillingService.swift",
                "Services/MicroCore/microcode_core.swift",
                "Views/HealerSuggestionView.swift",
                "Views/UniversalPreviewView.swift",
                "Views/Components/UniversalFilePreview.swift",
                "Views/Components/InteractiveImagePreviewView.swift",
                "Views/Components/UniversalSpreadsheetView.swift",
                "Views/Components/InteractivePDFPreviewView.swift",
                "Views/Components/VisualEffectView.swift",
                "Views/Components/AutocompletePopupView.swift",
                "Views/Components/DeviceFrameView.swift",
                "Views/Components/SnowEffectView.swift",
                "Views/Components/ThemePickerView.swift",
                "Views/Components/AuthenticEditor.swift",
                "Views/Components/AuthenticEditor+GhostText.swift",
                "Views/Components/AuthenticFileTree.swift",
                "Views/Components/AuthenticLogConsole.swift",
                "Views/Components/AuthenticTerminal.swift",
                "Views/Components/FestiveOverlayView.swift",
                "Views/Components/LineNumberRulerView.swift",
                "Views/Components/DraggableSplitView.swift",
                "Views/DatabaseStudioView.swift",
                "Views/APIClientView.swift",
                "Views/CICDPipelineView.swift",
                "Views/IDEBrowserView.swift",
                "Views/ModelBrowserSheet.swift",
                "Views/Settings/MicroCodeLicenseSettingsView.swift",
                "Views/TerminalTextView.swift",
                "Views/TerminalWebView.swift",
                "Views/Components/PlaygroundTerminalView.swift",
                "Views/Components/TransparentTerminalView.swift",
                "Views/DataFrameView.swift",
                "Kernel/KernelClient.swift",
                "Kernel/WebEngine.swift",
                "Kernel/ThemeEngine.swift",
                "Kernel/ExtensionSandbox.swift",
                "SyntaxEngine/Token.swift",
                "SyntaxEngine/Lexer.swift",
                "SyntaxEngine/AuthenticLexerAdapter.swift",
                "SyntaxEngine/ThemeManager.swift",
                "SyntaxEngine/SyntaxCache.swift",
                "SyntaxEngine/SyntaxHighlightingEngine.swift",
                "Services/SSHConfigParser.swift",
                "Services/RemoteWorkspaceManager.swift",
                "Services/SharedMemoryService.swift",
                "Views/ProjectRuntimeView.swift",
                "Views/EnvEditorView.swift",
                "Views/NodeProjectManagerView.swift",
                "Views/DataProfilingView.swift",
                "Views/Metal/MetalView.swift",
                "Views/Metal/MetalGridView.swift",
                "Views/Metal/CyberBackgroundView.swift",
                "Extensions/URLExtensions.swift",
                "Extensions/ColorExtensions.swift",
                "Extensions/Compatibility.swift",
                "Extensions/NSColor+Hex.swift",
                "Helpers/GraphemeHelper.swift",
                "Helpers/DeviceFrameAssets.swift",
            ],
            resources: [
                // .process("Views/Metal/Shaders.metal")
            ],
            swiftSettings: [
                .unsafeFlags(["-strict-concurrency=minimal"])
            ]
        ),
        .target(
            name: "MicrocodeCoreSupport",
            dependencies: [],
            path: "MicrocodeCoreSupport",
            publicHeadersPath: "include"
        )
    ],
    cxxLanguageStandard: .cxx17
)
