//
//  PythonScriptNotebookBridge.swift
//  MicroCode
//
//  Bidirectional converter between Notebook cells and plain-text Python scripts (# %%).
//  Eliminates Git merge conflicts and enables CI/CD direct execution.
//

import Foundation

struct PythonScriptNotebookBridge {
    
    /// Parses a plain Python script with `# %%` cell markers into NotebookCellModels
    static func parse(script: String) -> [NotebookCellModel] {
        var cells: [NotebookCellModel] = []
        let lines = script.components(separatedBy: .newlines)
        
        var currentLines: [String] = []
        var currentType: NotebookCellModel.CellType = .code
        var currentLang: CellLanguage = .python
        var isFirstCell = true
        
        func flushCell() {
            let content = currentLines.joined(separator: "\n").trimmingCharacters(in: .newlines)
            if !content.isEmpty || !cells.isEmpty {
                let cell = NotebookCellModel(type: currentType, language: currentLang, content: content)
                cells.append(cell)
            }
            currentLines = []
        }
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            
            // Check for # %% cell delimiter
            if trimmed.hasPrefix("# %%") || trimmed.hasPrefix("#%%") {
                if !isFirstCell || !currentLines.isEmpty {
                    flushCell()
                }
                isFirstCell = false
                
                let lower = trimmed.lowercased()
                if lower.contains("[markdown]") || lower.contains("md") {
                    currentType = .markdown
                    currentLang = .python
                } else if lower.contains("[bash]") || lower.contains("[sh]") {
                    currentType = .code
                    currentLang = .python
                } else {
                    currentType = .code
                    currentLang = .python
                }
                continue
            }
            
            // If markdown cell, strip leading "# " if present or keep markdown
            if currentType == .markdown && line.hasPrefix("# ") {
                currentLines.append(String(line.dropFirst(2)))
            } else if currentType == .markdown && line == "#" {
                currentLines.append("")
            } else {
                currentLines.append(line)
            }
        }
        
        flushCell()
        
        // Fallback: If no # %% markers were present, wrap entire script into 1 code cell
        if cells.isEmpty {
            let singleCell = NotebookCellModel(type: .code, language: .python, content: script)
            cells.append(singleCell)
        }
        
        return cells
    }
    
    /// Serializes NotebookCellModels into a clean, human-readable Python script with `# %%` markers
    static func export(cells: [NotebookCellModel]) -> String {
        var output: [String] = []
        
        output.append("#!/usr/bin/env python3")
        output.append("# -*- coding: utf-8 -*-")
        output.append("# Generated by MicroCode - Plain-Text Git-Friendly Notebook")
        output.append("")
        
        for cell in cells {
            switch cell.type {
            case .markdown:
                output.append("# %% [markdown]")
                let mdLines = cell.content.components(separatedBy: .newlines)
                for line in mdLines {
                    output.append("# " + line)
                }
                output.append("")
                
            case .code:
                output.append("# %% [python]")
                output.append(cell.content.trimmingCharacters(in: .newlines))
                output.append("")
                
            case .procedure:
                output.append("# %% [procedure]")
                output.append(cell.content.trimmingCharacters(in: .newlines))
                output.append("")
                
            case .agent:
                output.append("# %% [agent]")
                output.append("# " + cell.content.replacingOccurrences(of: "\n", with: "\n# "))
                output.append("")
                
            case .raw:
                output.append("# %% [raw]")
                output.append(cell.content.trimmingCharacters(in: .newlines))
                output.append("")
            }
        }
        
        return output.joined(separator: "\n")
    }
}
